[keys.normal]
"C-c" = "no_op"
"C-f" = ["collapse_selection", "keep_primary_selection"]
"C-v" = "vsplit"
"C-n" = "rotate_view"
"S-tab" = "unindent"

[keys.insert]
"C-f" = "normal_mode"
"S-tab" = "unindent"

[keys.select]
"C-c" = "no_op"
"C-f" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-v" = "vsplit"
"C-n" = "rotate_view"

[editor]
whitespace.render = "all"
smart-tab.enable = false
auto-pairs = false

[editor.whitespace.characters]
space = " "
tab = "→"
newline = "↵"
